name: Lint Deploy Test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Download Project NPM
        run: npm i

      - name: Run Tests
        run: npm run test
      
      - name: Run Lint
        run: npm run lint
      
      - name: Run Deploy
        run: echo "Deploy in progress"

  test2-concurrently-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Download Project NPM
        run: npm i

      - name: Run Tests
        run: npm run test
    
  test2-concurrently-lint:
    needs: test2-concurrently-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Download Project NPM
        run: npm i
      
      - name: Run Lint
        run: npm run lint
      
      - name: Run Deploy
        run: echo "Deploy in progress"

  test2-concurrently-deploy:
    needs: test2-concurrently-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Download Project NPM
        run: npm i
      
      - name: Run Deploy
        run: echo "Deploy in progress"